vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       recipes_images:
           uri_prefix: /images/recipes
           upload_destination: '%kernel.project_dir%/public/images/recipes'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
